# KML文件处理工作流配置
name: KML文件处理工作流

# 触发器
trigger:
  type: file_upload
  config:
    directory: d:\ProjectS\snowagent\frontend\snowagent-web\public
    patterns:
      - '*.kml'
    recursive: false

# 工作流步骤
steps:
  # 步骤1: 运行KML处理脚本
  - name: 处理KML文件
    type: script
    config:
      script_path: d:\ProjectS\snowagent\backend\app\task\process_kml.py
      working_directory: d:\ProjectS\snowagent\backend\app\task
      timeout: 300  # 5分钟超时

  # 步骤2: 验证处理结果
  - name: 验证处理结果
    type: file_check
    config:
      files:
        - pattern: d:\ProjectS\snowagent\frontend\snowagent-web\public\*1.0.1.kml
        - pattern: d:\ProjectS\snowagent\frontend\snowagent-web\public\*1.0.1.kml

  # 步骤3: 通知完成
  - name: 通知处理完成
    type: notification
    config:
      message: "KML文件处理完成，已生成新版本文件"
      recipients:
        - system

# 错误处理
error_handling:
  on_error:
    - name: 错误通知
      type: notification
      config:
        message: "KML文件处理失败: {{error.message}}"
        recipients:
          - system

# 工作流配置
config:
  max_retries: 3
  retry_delay: 60  # 秒
  concurrency: 1  # 同时只能处理一个文件
